name: Deploy to Curse

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pack and Ship to Curse
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_TOKEN }}
          CURSE_PROJECT_ID: ${{ secrets.CF_PROJECT_ID }}
